--liquibase formatted sql

--changeset admissions:001-workflow-and-classes
--comment Academic years, workflow definition (stages, transitions) and per-class configuration

CREATE TABLE academic_year (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            VARCHAR(20) NOT NULL,
    starts_on        DATE NOT NULL,
    ends_on          DATE NOT NULL,
    age_cutoff_date  DATE NOT NULL,
    admissions_open  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_academic_year_label UNIQUE (label)
);

CREATE TABLE workflow (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    version  INT NOT NULL DEFAULT 1,
    status   VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT uq_workflow UNIQUE (name, version),
    CONSTRAINT ck_workflow_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE stage_definition (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id  BIGINT NOT NULL,
    code         VARCHAR(30) NOT NULL,
    name         VARCHAR(60) NOT NULL,
    seq_no       INT NOT NULL,
    category     VARCHAR(20) NOT NULL,
    CONSTRAINT fk_stage_workflow FOREIGN KEY (workflow_id) REFERENCES workflow (id),
    CONSTRAINT uq_stage_code UNIQUE (workflow_id, code),
    CONSTRAINT ck_stage_category CHECK (category IN ('OPEN', 'HOLD', 'TERMINAL_SUCCESS', 'TERMINAL_FAIL'))
);

-- allowed_roles / guard_keys / action_keys are comma-separated lists so the schema stays portable
CREATE TABLE stage_transition (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT NOT NULL,
    from_stage_id  BIGINT NOT NULL,
    to_stage_id    BIGINT NOT NULL,
    allowed_roles  VARCHAR(255) NOT NULL,
    guard_keys     VARCHAR(255) NOT NULL DEFAULT '',
    action_keys    VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT fk_transition_workflow FOREIGN KEY (workflow_id) REFERENCES workflow (id),
    CONSTRAINT fk_transition_from FOREIGN KEY (from_stage_id) REFERENCES stage_definition (id),
    CONSTRAINT fk_transition_to FOREIGN KEY (to_stage_id) REFERENCES stage_definition (id),
    CONSTRAINT uq_transition UNIQUE (from_stage_id, to_stage_id)
);

CREATE TABLE class_config (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  BIGINT NOT NULL,
    class_code        VARCHAR(20) NOT NULL,
    display_name      VARCHAR(60) NOT NULL,
    min_age_years     INT,
    max_age_years     INT,
    seats_total       INT NOT NULL,
    seats_pre_filled  INT NOT NULL DEFAULT 0,
    pass_mark         NUMERIC(5, 2) NOT NULL DEFAULT 50,
    admission_fee     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fee_due_days      INT NOT NULL DEFAULT 5,
    workflow_id       BIGINT NOT NULL,
    CONSTRAINT fk_class_year FOREIGN KEY (academic_year_id) REFERENCES academic_year (id),
    CONSTRAINT fk_class_workflow FOREIGN KEY (workflow_id) REFERENCES workflow (id),
    CONSTRAINT uq_class UNIQUE (academic_year_id, class_code),
    CONSTRAINT ck_class_seats CHECK (seats_total >= 0 AND seats_pre_filled >= 0)
);

CREATE TABLE required_document (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_config_id  BIGINT NOT NULL,
    doc_type         VARCHAR(30) NOT NULL,
    mandatory        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_reqdoc_class FOREIGN KEY (class_config_id) REFERENCES class_config (id) ON DELETE CASCADE,
    CONSTRAINT uq_reqdoc UNIQUE (class_config_id, doc_type)
);

--rollback DROP TABLE required_document;
--rollback DROP TABLE class_config;
--rollback DROP TABLE stage_transition;
--rollback DROP TABLE stage_definition;
--rollback DROP TABLE workflow;
--rollback DROP TABLE academic_year;

--changeset admissions:002-users
CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    full_name      VARCHAR(100) NOT NULL,
    email          VARCHAR(150),
    phone          VARCHAR(20),
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE user_role (
    user_id  BIGINT NOT NULL,
    role     VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

--rollback DROP TABLE user_role;
--rollback DROP TABLE app_user;

--changeset admissions:003-forms
--comment Versioned, admin-configurable application forms
CREATE TABLE form_definition (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    purpose       VARCHAR(20) NOT NULL,
    version       INT NOT NULL DEFAULT 1,
    status        VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_form UNIQUE (name, version),
    CONSTRAINT ck_form_purpose CHECK (purpose IN ('ENQUIRY', 'APPLICATION')),
    CONSTRAINT ck_form_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE form_field (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_definition_id  BIGINT NOT NULL,
    field_key           VARCHAR(60) NOT NULL,
    label               VARCHAR(150) NOT NULL,
    field_type          VARCHAR(20) NOT NULL,
    mandatory           BOOLEAN NOT NULL DEFAULT FALSE,
    seq_no              INT NOT NULL,
    options             VARCHAR(1000),
    CONSTRAINT fk_field_form FOREIGN KEY (form_definition_id) REFERENCES form_definition (id) ON DELETE CASCADE,
    CONSTRAINT uq_field_key UNIQUE (form_definition_id, field_key),
    CONSTRAINT uq_field_seq UNIQUE (form_definition_id, seq_no),
    CONSTRAINT ck_field_type CHECK (field_type IN ('TEXT', 'NUMBER', 'DATE', 'SELECT', 'CHECKBOX', 'TEXTAREA', 'PHONE', 'EMAIL'))
);

--rollback DROP TABLE form_field;
--rollback DROP TABLE form_definition;

--changeset admissions:004-leads-and-applications
CREATE TABLE lead (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_name      VARCHAR(100) NOT NULL,
    phone              VARCHAR(20) NOT NULL,
    email              VARCHAR(150),
    child_name         VARCHAR(100),
    child_dob          DATE,
    class_code         VARCHAR(20),
    source             VARCHAR(30) NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'NEW',
    lost_reason        VARCHAR(200),
    consent            BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_to_id     BIGINT,
    next_follow_up_at  TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lead_assignee FOREIGN KEY (assigned_to_id) REFERENCES app_user (id),
    CONSTRAINT ck_lead_status CHECK (status IN ('NEW', 'CONTACTED', 'INTERESTED', 'VISIT_SCHEDULED', 'CONVERTED', 'LOST'))
);
CREATE INDEX ix_lead_phone ON lead (phone, child_dob);
CREATE INDEX ix_lead_status ON lead (status);

CREATE TABLE lead_followup (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id        BIGINT NOT NULL,
    due_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    done_at        TIMESTAMP WITH TIME ZONE,
    note           VARCHAR(500),
    created_by_id  BIGINT,
    CONSTRAINT fk_followup_lead FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE CASCADE,
    CONSTRAINT fk_followup_user FOREIGN KEY (created_by_id) REFERENCES app_user (id)
);

CREATE TABLE application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no      VARCHAR(30) NOT NULL,
    academic_year_id    BIGINT NOT NULL,
    class_config_id     BIGINT NOT NULL,
    workflow_id         BIGINT NOT NULL,
    stage_id            BIGINT NOT NULL,
    prev_stage_id       BIGINT,
    lead_id             BIGINT,
    guardian_user_id    BIGINT,
    assigned_to_id      BIGINT,
    child_name          VARCHAR(100),
    child_dob           DATE,
    gender              VARCHAR(20),
    previous_school     VARCHAR(150),
    guardian_name       VARCHAR(100),
    guardian_phone      VARCHAR(20),
    guardian_email      VARCHAR(150),
    form_definition_id  BIGINT,
    form_version        INT,
    responses           TEXT,
    submitted_at        TIMESTAMP WITH TIME ZONE,
    admission_no        VARCHAR(30),
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_application_no UNIQUE (application_no),
    CONSTRAINT uq_admission_no UNIQUE (admission_no),
    CONSTRAINT fk_app_year FOREIGN KEY (academic_year_id) REFERENCES academic_year (id),
    CONSTRAINT fk_app_class FOREIGN KEY (class_config_id) REFERENCES class_config (id),
    CONSTRAINT fk_app_workflow FOREIGN KEY (workflow_id) REFERENCES workflow (id),
    CONSTRAINT fk_app_stage FOREIGN KEY (stage_id) REFERENCES stage_definition (id),
    CONSTRAINT fk_app_prev_stage FOREIGN KEY (prev_stage_id) REFERENCES stage_definition (id),
    CONSTRAINT fk_app_lead FOREIGN KEY (lead_id) REFERENCES lead (id),
    CONSTRAINT fk_app_guardian FOREIGN KEY (guardian_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_app_assignee FOREIGN KEY (assigned_to_id) REFERENCES app_user (id),
    CONSTRAINT fk_app_form FOREIGN KEY (form_definition_id) REFERENCES form_definition (id)
);
CREATE INDEX ix_application_stage ON application (stage_id);
CREATE INDEX ix_application_class ON application (class_config_id);
CREATE INDEX ix_application_guardian ON application (guardian_user_id);
CREATE INDEX ix_application_assignee ON application (assigned_to_id);

--rollback DROP TABLE application;
--rollback DROP TABLE lead_followup;
--rollback DROP TABLE lead;

--changeset admissions:005-documents-seats-assessment
CREATE TABLE application_document (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,
    doc_type             VARCHAR(30) NOT NULL,
    file_name            VARCHAR(255) NOT NULL,
    content_type         VARCHAR(100) NOT NULL,
    size_bytes           BIGINT NOT NULL,
    storage_key          VARCHAR(400) NOT NULL,
    verification_status  VARCHAR(20) NOT NULL DEFAULT 'UPLOADED',
    reject_reason        VARCHAR(300),
    verified_by_id       BIGINT,
    verified_at          TIMESTAMP WITH TIME ZONE,
    uploaded_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_application FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_verifier FOREIGN KEY (verified_by_id) REFERENCES app_user (id),
    CONSTRAINT ck_doc_status CHECK (verification_status IN ('UPLOADED', 'VERIFIED', 'REJECTED'))
);
CREATE INDEX ix_doc_application ON application_document (application_id, doc_type);

-- One ledger row per application. The status moves HELD -> CONFIRMED, or RELEASED when the seat is given back.
CREATE TABLE seat_allocation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_config_id  BIGINT NOT NULL,
    application_id   BIGINT NOT NULL,
    status           VARCHAR(20) NOT NULL,
    held_until       TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seat_class FOREIGN KEY (class_config_id) REFERENCES class_config (id),
    CONSTRAINT fk_seat_application FOREIGN KEY (application_id) REFERENCES application (id),
    CONSTRAINT uq_seat_application UNIQUE (application_id),
    CONSTRAINT ck_seat_status CHECK (status IN ('HELD', 'CONFIRMED', 'RELEASED'))
);
CREATE INDEX ix_seat_class ON seat_allocation (class_config_id, status);

CREATE TABLE interaction_slot (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       VARCHAR(20) NOT NULL,
    starts_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    capacity   INT NOT NULL,
    booked     INT NOT NULL DEFAULT 0,
    CONSTRAINT ck_slot_kind CHECK (kind IN ('INTERACTION', 'CAMPUS_TOUR', 'ENTRANCE_TEST')),
    CONSTRAINT ck_slot_capacity CHECK (capacity > 0 AND booked >= 0 AND booked <= capacity)
);

CREATE TABLE interaction_booking (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id         BIGINT NOT NULL,
    application_id  BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
    CONSTRAINT fk_booking_slot FOREIGN KEY (slot_id) REFERENCES interaction_slot (id),
    CONSTRAINT fk_booking_application FOREIGN KEY (application_id) REFERENCES application (id),
    CONSTRAINT uq_booking UNIQUE (slot_id, application_id),
    CONSTRAINT ck_booking_status CHECK (status IN ('BOOKED', 'ATTENDED', 'NO_SHOW', 'CANCELLED'))
);

CREATE TABLE assessment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id   BIGINT NOT NULL,
    kind             VARCHAR(20) NOT NULL,
    score            NUMERIC(5, 2) NOT NULL,
    passed           BOOLEAN NOT NULL,
    remarks          VARCHAR(500),
    evaluated_by_id  BIGINT,
    evaluated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assessment_application FOREIGN KEY (application_id) REFERENCES application (id),
    CONSTRAINT fk_assessment_user FOREIGN KEY (evaluated_by_id) REFERENCES app_user (id),
    CONSTRAINT ck_assessment_kind CHECK (kind IN ('INTERACTION', 'ENTRANCE_TEST'))
);
CREATE INDEX ix_assessment_application ON assessment (application_id);

--rollback DROP TABLE assessment;
--rollback DROP TABLE interaction_booking;
--rollback DROP TABLE interaction_slot;
--rollback DROP TABLE seat_allocation;
--rollback DROP TABLE application_document;

--changeset admissions:006-payments
CREATE TABLE invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no      VARCHAR(40) NOT NULL,
    application_id  BIGINT NOT NULL,
    description     VARCHAR(200) NOT NULL,
    amount          NUMERIC(12, 2) NOT NULL,
    currency        VARCHAR(3) NOT NULL DEFAULT 'INR',
    status          VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    issued_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_invoice_no UNIQUE (invoice_no),
    CONSTRAINT fk_invoice_application FOREIGN KEY (application_id) REFERENCES application (id),
    CONSTRAINT ck_invoice_status CHECK (status IN ('ISSUED', 'PAID', 'CANCELLED', 'EXPIRED'))
);
CREATE INDEX ix_invoice_application ON invoice (application_id, status);

CREATE TABLE payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL,
    gateway             VARCHAR(30) NOT NULL,
    gateway_order_id    VARCHAR(100) NOT NULL,
    gateway_payment_id  VARCHAR(100),
    idempotency_key     VARCHAR(100) NOT NULL,
    amount              NUMERIC(12, 2) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'INITIATED',
    method              VARCHAR(20),
    settled_at          TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT uq_payment_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_order UNIQUE (gateway, gateway_order_id),
    CONSTRAINT ck_payment_status CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

-- Each gateway event is stored once. The unique key turns a redelivery into a harmless no-op.
CREATE TABLE payment_webhook_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway       VARCHAR(30) NOT NULL,
    event_id      VARCHAR(100) NOT NULL,
    payload       TEXT NOT NULL,
    received_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at  TIMESTAMP WITH TIME ZONE,
    note          VARCHAR(300),
    CONSTRAINT uq_webhook_event UNIQUE (gateway, event_id)
);

--rollback DROP TABLE payment_webhook_event;
--rollback DROP TABLE payment;
--rollback DROP TABLE invoice;

--changeset admissions:007-communication-history-outbox
CREATE TABLE message_template (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code     VARCHAR(50) NOT NULL,
    channel  VARCHAR(20) NOT NULL,
    body     VARCHAR(1000) NOT NULL,
    CONSTRAINT uq_template UNIQUE (code, channel),
    CONSTRAINT ck_template_channel CHECK (channel IN ('WHATSAPP', 'SMS', 'EMAIL'))
);

CREATE TABLE communication_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id  BIGINT NOT NULL,
    channel         VARCHAR(20) NOT NULL,
    template_code   VARCHAR(50) NOT NULL,
    to_address      VARCHAR(150),
    message         VARCHAR(1000) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    error           VARCHAR(300),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comm_application FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE
);
CREATE INDEX ix_comm_application ON communication_log (application_id, created_at);

-- Append-only in the application code (no update or delete paths exist)
CREATE TABLE stage_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id  BIGINT NOT NULL,
    from_stage_id   BIGINT,
    to_stage_id     BIGINT NOT NULL,
    actor_type      VARCHAR(20) NOT NULL,
    actor_id        VARCHAR(50),
    reason          VARCHAR(300),
    changed_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_history_application FOREIGN KEY (application_id) REFERENCES application (id),
    CONSTRAINT fk_history_from FOREIGN KEY (from_stage_id) REFERENCES stage_definition (id),
    CONSTRAINT fk_history_to FOREIGN KEY (to_stage_id) REFERENCES stage_definition (id),
    CONSTRAINT ck_history_actor CHECK (actor_type IN ('GUARDIAN', 'STAFF', 'SYSTEM'))
);
CREATE INDEX ix_history_application ON stage_history (application_id, id);

-- Transactional outbox: written in the same transaction as the state change, relayed by OutboxRelay
CREATE TABLE outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(40) NOT NULL,
    aggregate_id    BIGINT NOT NULL,
    event_type      VARCHAR(60) NOT NULL,
    payload         TEXT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP WITH TIME ZONE,
    attempts        INT NOT NULL DEFAULT 0
);
CREATE INDEX ix_outbox_pending ON outbox_event (published_at, id);

--rollback DROP TABLE outbox_event;
--rollback DROP TABLE stage_history;
--rollback DROP TABLE communication_log;
--rollback DROP TABLE message_template;
