--liquibase formatted sql

--changeset erp:001-core-school-erp
--comment Core School ERP modules for students, attendance, fees, timetable, examinations, transport, notifications and certificates.

CREATE TABLE student (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_no      VARCHAR(30) NOT NULL,
    roll_no           VARCHAR(20),
    academic_year_id  BIGINT NOT NULL,
    class_config_id   BIGINT NOT NULL,
    guardian_user_id  BIGINT,
    full_name         VARCHAR(120) NOT NULL,
    dob               DATE,
    gender            VARCHAR(20),
    blood_group       VARCHAR(10),
    house_name        VARCHAR(40),
    guardian_name     VARCHAR(120),
    guardian_phone    VARCHAR(20),
    guardian_email    VARCHAR(150),
    address_line      VARCHAR(400),
    status            VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_on         DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_admission_no UNIQUE (admission_no),
    CONSTRAINT fk_student_year FOREIGN KEY (academic_year_id) REFERENCES academic_year(id),
    CONSTRAINT fk_student_class FOREIGN KEY (class_config_id) REFERENCES class_config(id),
    CONSTRAINT fk_student_guardian FOREIGN KEY (guardian_user_id) REFERENCES app_user(id),
    CONSTRAINT ck_student_status CHECK (status IN ('ACTIVE','INACTIVE','ALUMNI','WITHDRAWN'))
);

CREATE TABLE attendance_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    attendance_on DATE NOT NULL,
    status        VARCHAR(20) NOT NULL,
    remarks       VARCHAR(250),
    marked_by_id  BIGINT,
    marked_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_att_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT fk_att_marker FOREIGN KEY (marked_by_id) REFERENCES app_user(id),
    CONSTRAINT uq_attendance UNIQUE(student_id, attendance_on),
    CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT','ABSENT','LATE','HALF_DAY','LEAVE'))
);

CREATE TABLE student_fee_due (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    fee_type      VARCHAR(50) NOT NULL,
    term_name     VARCHAR(50) NOT NULL,
    amount        NUMERIC(12,2) NOT NULL,
    paid_amount   NUMERIC(12,2) NOT NULL DEFAULT 0,
    due_date      DATE NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'DUE',
    paid_on       DATE,
    payment_mode  VARCHAR(30),
    reference_no  VARCHAR(80),
    CONSTRAINT fk_fee_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT ck_fee_status CHECK (status IN ('DUE','PARTIAL','PAID','WAIVED','OVERDUE'))
);

CREATE TABLE timetable_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_config_id   BIGINT NOT NULL,
    day_of_week       VARCHAR(10) NOT NULL,
    period_no         INT NOT NULL,
    starts_at         TIME NOT NULL,
    ends_at           TIME NOT NULL,
    subject_name      VARCHAR(80) NOT NULL,
    teacher_user_id   BIGINT,
    room_name         VARCHAR(50),
    CONSTRAINT fk_tt_class FOREIGN KEY (class_config_id) REFERENCES class_config(id) ON DELETE CASCADE,
    CONSTRAINT fk_tt_teacher FOREIGN KEY (teacher_user_id) REFERENCES app_user(id),
    CONSTRAINT uq_tt_period UNIQUE(class_config_id, day_of_week, period_no)
);

CREATE TABLE exam (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  BIGINT NOT NULL,
    name              VARCHAR(100) NOT NULL,
    term_name         VARCHAR(50),
    starts_on         DATE,
    ends_on           DATE,
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_exam_year FOREIGN KEY (academic_year_id) REFERENCES academic_year(id),
    CONSTRAINT ck_exam_status CHECK (status IN ('DRAFT','SCHEDULED','ONGOING','COMPLETED','PUBLISHED'))
);

CREATE TABLE exam_subject (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id           BIGINT NOT NULL,
    class_config_id   BIGINT NOT NULL,
    subject_name      VARCHAR(80) NOT NULL,
    max_marks         NUMERIC(6,2) NOT NULL DEFAULT 100,
    pass_marks        NUMERIC(6,2) NOT NULL DEFAULT 33,
    exam_date         DATE,
    CONSTRAINT fk_exam_subject_exam FOREIGN KEY (exam_id) REFERENCES exam(id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_subject_class FOREIGN KEY (class_config_id) REFERENCES class_config(id) ON DELETE CASCADE,
    CONSTRAINT uq_exam_subject UNIQUE(exam_id, class_config_id, subject_name)
);

CREATE TABLE student_mark (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT NOT NULL,
    exam_subject_id   BIGINT NOT NULL,
    marks_obtained    NUMERIC(6,2),
    grade             VARCHAR(5),
    remarks           VARCHAR(250),
    entered_by_id     BIGINT,
    entered_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mark_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT fk_mark_subject FOREIGN KEY (exam_subject_id) REFERENCES exam_subject(id) ON DELETE CASCADE,
    CONSTRAINT fk_mark_teacher FOREIGN KEY (entered_by_id) REFERENCES app_user(id),
    CONSTRAINT uq_student_mark UNIQUE(student_id, exam_subject_id)
);

CREATE TABLE transport_route (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_code     VARCHAR(20) NOT NULL,
    route_name     VARCHAR(100) NOT NULL,
    vehicle_no     VARCHAR(30),
    driver_name    VARCHAR(100),
    driver_phone   VARCHAR(20),
    attendant_name VARCHAR(100),
    capacity       INT NOT NULL DEFAULT 40,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_transport_route UNIQUE(route_code)
);

CREATE TABLE transport_stop (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id       BIGINT NOT NULL,
    stop_name      VARCHAR(100) NOT NULL,
    pickup_time    TIME,
    drop_time      TIME,
    seq_no         INT NOT NULL,
    monthly_fee    NUMERIC(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_stop_route FOREIGN KEY (route_id) REFERENCES transport_route(id) ON DELETE CASCADE,
    CONSTRAINT uq_route_stop UNIQUE(route_id, seq_no)
);

CREATE TABLE student_transport (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     BIGINT NOT NULL,
    route_id       BIGINT NOT NULL,
    stop_id        BIGINT NOT NULL,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_st_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT fk_st_route FOREIGN KEY (route_id) REFERENCES transport_route(id),
    CONSTRAINT fk_st_stop FOREIGN KEY (stop_id) REFERENCES transport_stop(id)
);

CREATE TABLE user_notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    title       VARCHAR(160) NOT NULL,
    body        VARCHAR(1000) NOT NULL,
    category    VARCHAR(30) NOT NULL DEFAULT 'GENERAL',
    read_flag   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE TABLE student_certificate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    certificate_no  VARCHAR(40) NOT NULL,
    certificate_type VARCHAR(40) NOT NULL,
    title           VARCHAR(160) NOT NULL,
    body_text       VARCHAR(2000) NOT NULL,
    issued_on       DATE NOT NULL DEFAULT CURRENT_DATE,
    issued_by_id    BIGINT,
    CONSTRAINT fk_certificate_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT fk_certificate_issuer FOREIGN KEY (issued_by_id) REFERENCES app_user(id),
    CONSTRAINT uq_certificate_no UNIQUE(certificate_no)
);

--rollback DROP TABLE student_certificate;
--rollback DROP TABLE user_notification;
--rollback DROP TABLE student_transport;
--rollback DROP TABLE transport_stop;
--rollback DROP TABLE transport_route;
--rollback DROP TABLE student_mark;
--rollback DROP TABLE exam_subject;
--rollback DROP TABLE exam;
--rollback DROP TABLE timetable_entry;
--rollback DROP TABLE student_fee_due;
--rollback DROP TABLE attendance_record;
--rollback DROP TABLE student;

--changeset erp:002-demo-users context:demo
INSERT INTO app_user (username, password_hash, full_name, email, phone) VALUES
    ('principal', '{bcrypt}$2a$10$9UUKzJp1Yxmn.EojUA36He1hl.QXU5Te5mlQESGtlusXEfbZnbN4.', 'Dr. Kavita Iyer', 'principal@school.test', '+919810000020'),
    ('teacher1',  '{bcrypt}$2a$10$9UUKzJp1Yxmn.EojUA36He1hl.QXU5Te5mlQESGtlusXEfbZnbN4.', 'Ananya Joshi', 'ananya.joshi@school.test', '+919810000021'),
    ('teacher2',  '{bcrypt}$2a$10$9UUKzJp1Yxmn.EojUA36He1hl.QXU5Te5mlQESGtlusXEfbZnbN4.', 'Arjun Nair', 'arjun.nair@school.test', '+919810000022');

INSERT INTO user_role (user_id, role)
SELECT u.id, v.role FROM (VALUES
    ('principal','PRINCIPAL'), ('teacher1','TEACHER'), ('teacher2','TEACHER')
) AS v(username, role) JOIN app_user u ON u.username=v.username;

-- Make the existing admin account a management user too.
INSERT INTO user_role (user_id, role)
SELECT id, 'PRINCIPAL' FROM app_user WHERE username='admin';

--rollback DELETE FROM user_role WHERE role IN ('PRINCIPAL','TEACHER');
--rollback DELETE FROM app_user WHERE username IN ('principal','teacher1','teacher2');

--changeset erp:003-demo-students context:demo
INSERT INTO student (admission_no, roll_no, academic_year_id, class_config_id, guardian_user_id, full_name, dob, gender, blood_group, house_name, guardian_name, guardian_phone, guardian_email, address_line, status, joined_on)
SELECT v.adm, v.roll, ay.id, c.id, g.id, v.name, CAST(v.dob AS DATE), v.gender, v.blood, v.house, v.guardian, v.phone, v.email, v.address, 'ACTIVE', CAST(v.joined AS DATE)
FROM (VALUES
 ('ADM27-00001','01','C1','Aanya Sharma','2020-08-14','Female','B+','Tagore','Neha Sharma','+919810000001','neha.sharma@example.com','Indiranagar, Bengaluru','2027-04-01','parent'),
 ('ADM27-00002','02','C1','Diya Nair','2020-02-02','Female','O+','Ashoka','Anil Nair','+919820000103','anil.n@example.com','Whitefield, Bengaluru','2027-04-01',NULL),
 ('ADM27-00003','03','C1','Vihaan Mehta','2020-11-03','Male','A+','Tagore','Rohan Mehta','+919820000101','rohan.m@example.com','Koramangala, Bengaluru','2027-04-01',NULL),
 ('ADM27-00007','07','LKG','Tara Bose','2022-03-14','Female','B+','Raman','Debashish Bose','+919820000107','deb.b@example.com','HSR Layout, Bengaluru','2027-04-01',NULL),
 ('ADM27-00021','21','C6','Reyansh Gupta','2015-05-20','Male','O+','Ashoka','Sanjay Gupta','+919820000105','sanjay.g@example.com','Jayanagar, Bengaluru','2027-04-01',NULL),
 ('ADM27-00022','22','C6','Myra Khan','2015-01-09','Female','A-','Raman','Imran Khan','+919820000106','imran.k@example.com','BTM Layout, Bengaluru','2027-04-01',NULL),
 ('ADM27-00031','11','C9','Ishaan Verma','2012-10-30','Male','B-','Tagore','Kavita Verma','+919820000108','kavita.v@example.com','JP Nagar, Bengaluru','2027-04-01',NULL),
 ('ADM27-00045','18','C12','Aarav Rao','2009-07-16','Male','AB+','Ashoka','Manish Rao','+919820000145','manish.rao@example.com','Malleshwaram, Bengaluru','2027-04-01',NULL)
) AS v(adm,roll,class_code,name,dob,gender,blood,house,guardian,phone,email,address,joined,parent_username)
JOIN academic_year ay ON ay.label='2027-28'
JOIN class_config c ON c.academic_year_id=ay.id AND c.class_code=v.class_code
LEFT JOIN app_user g ON g.username=v.parent_username;

--rollback DELETE FROM student;

--changeset erp:004-demo-attendance-fees context:demo
INSERT INTO attendance_record (student_id, attendance_on, status, remarks, marked_by_id)
SELECT s.id, DATEADD(DAY, -d.day_ago, CURRENT_DATE),
       CASE WHEN MOD(s.id + d.day_ago, 13)=0 THEN 'ABSENT' WHEN MOD(s.id + d.day_ago, 9)=0 THEN 'LATE' ELSE 'PRESENT' END,
       NULL, (SELECT id FROM app_user WHERE username='teacher1')
FROM student s
CROSS JOIN (VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20)) d(day_ago);

INSERT INTO student_fee_due (student_id, fee_type, term_name, amount, paid_amount, due_date, status, paid_on, payment_mode, reference_no)
SELECT s.id, v.fee_type, v.term_name, v.amount,
       CASE WHEN MOD(s.id + v.seq_no, 4)=0 THEN v.amount WHEN MOD(s.id + v.seq_no, 5)=0 THEN v.amount/2 ELSE 0 END,
       DATEADD(DAY, v.due_in, CURRENT_DATE),
       CASE WHEN MOD(s.id + v.seq_no, 4)=0 THEN 'PAID' WHEN MOD(s.id + v.seq_no, 5)=0 THEN 'PARTIAL' WHEN v.due_in < 0 THEN 'OVERDUE' ELSE 'DUE' END,
       CASE WHEN MOD(s.id + v.seq_no, 4)=0 THEN DATEADD(DAY,-4,CURRENT_DATE) ELSE NULL END,
       CASE WHEN MOD(s.id + v.seq_no, 4)=0 THEN 'UPI' ELSE NULL END,
       CASE WHEN MOD(s.id + v.seq_no, 4)=0 THEN 'TXN-DEMO-' || s.id || '-' || v.seq_no ELSE NULL END
FROM student s
CROSS JOIN (VALUES
 (1,'TUITION','Term 1',18000, -10),
 (2,'ACTIVITY','Annual',3500, 15),
 (3,'TUITION','Term 2',18000, 60)
) v(seq_no,fee_type,term_name,amount,due_in);

--rollback DELETE FROM student_fee_due;
--rollback DELETE FROM attendance_record;

--changeset erp:005-demo-timetable context:demo
INSERT INTO timetable_entry (class_config_id, day_of_week, period_no, starts_at, ends_at, subject_name, teacher_user_id, room_name)
SELECT c.id, v.day_name, v.period_no, CAST(v.start_at AS TIME), CAST(v.end_at AS TIME), v.subject,
       (SELECT id FROM app_user WHERE username=CASE WHEN v.teacher_no=1 THEN 'teacher1' ELSE 'teacher2' END), v.room_name
FROM class_config c
CROSS JOIN (VALUES
 ('MONDAY',1,'08:30:00','09:10:00','English',1,'Room 101'),
 ('MONDAY',2,'09:10:00','09:50:00','Mathematics',2,'Room 101'),
 ('MONDAY',3,'10:10:00','10:50:00','Science',1,'Lab / Room'),
 ('MONDAY',4,'10:50:00','11:30:00','Hindi',2,'Room 101'),
 ('TUESDAY',1,'08:30:00','09:10:00','Mathematics',2,'Room 101'),
 ('TUESDAY',2,'09:10:00','09:50:00','English',1,'Room 101'),
 ('TUESDAY',3,'10:10:00','10:50:00','Social Studies',2,'Room 101'),
 ('TUESDAY',4,'10:50:00','11:30:00','Computer Science',1,'Computer Lab'),
 ('WEDNESDAY',1,'08:30:00','09:10:00','Science',1,'Lab / Room'),
 ('WEDNESDAY',2,'09:10:00','09:50:00','Mathematics',2,'Room 101'),
 ('WEDNESDAY',3,'10:10:00','10:50:00','English',1,'Room 101'),
 ('WEDNESDAY',4,'10:50:00','11:30:00','Physical Education',2,'Ground'),
 ('THURSDAY',1,'08:30:00','09:10:00','Hindi',2,'Room 101'),
 ('THURSDAY',2,'09:10:00','09:50:00','Science',1,'Lab / Room'),
 ('THURSDAY',3,'10:10:00','10:50:00','Mathematics',2,'Room 101'),
 ('THURSDAY',4,'10:50:00','11:30:00','Art',1,'Art Room'),
 ('FRIDAY',1,'08:30:00','09:10:00','English',1,'Room 101'),
 ('FRIDAY',2,'09:10:00','09:50:00','Social Studies',2,'Room 101'),
 ('FRIDAY',3,'10:10:00','10:50:00','Computer Science',1,'Computer Lab'),
 ('FRIDAY',4,'10:50:00','11:30:00','Library',2,'Library')
) v(day_name,period_no,start_at,end_at,subject,teacher_no,room_name)
WHERE c.class_code IN ('C1','C6','C9','C12');

--rollback DELETE FROM timetable_entry;

--changeset erp:006-demo-exams-marks context:demo
INSERT INTO exam (academic_year_id, name, term_name, starts_on, ends_on, status, published_at)
SELECT id, 'Half Yearly Examination', 'Term 1', DATEADD(DAY,-35,CURRENT_DATE), DATEADD(DAY,-28,CURRENT_DATE), 'PUBLISHED', DATEADD(DAY,-20,CURRENT_TIMESTAMP)
FROM academic_year WHERE label='2027-28';

INSERT INTO exam (academic_year_id, name, term_name, starts_on, ends_on, status)
SELECT id, 'Annual Examination', 'Term 2', DATEADD(DAY,90,CURRENT_DATE), DATEADD(DAY,100,CURRENT_DATE), 'SCHEDULED'
FROM academic_year WHERE label='2027-28';

INSERT INTO exam_subject (exam_id, class_config_id, subject_name, max_marks, pass_marks, exam_date)
SELECT e.id, c.id, v.subject, 100, 33, DATEADD(DAY,v.offset_days,e.starts_on)
FROM exam e
JOIN class_config c ON c.academic_year_id=e.academic_year_id AND c.class_code IN ('C1','C6','C9','C12')
CROSS JOIN (VALUES ('English',0),('Mathematics',1),('Science',2),('Hindi',3),('Social Studies',4)) v(subject,offset_days)
WHERE e.name='Half Yearly Examination';

INSERT INTO student_mark (student_id, exam_subject_id, marks_obtained, grade, remarks, entered_by_id)
SELECT s.id, es.id,
       CAST(58 + MOD((s.id * 7 + es.id * 3), 38) AS NUMERIC(6,2)),
       CASE WHEN 58 + MOD((s.id * 7 + es.id * 3), 38) >= 90 THEN 'A1'
            WHEN 58 + MOD((s.id * 7 + es.id * 3), 38) >= 80 THEN 'A2'
            WHEN 58 + MOD((s.id * 7 + es.id * 3), 38) >= 70 THEN 'B1'
            WHEN 58 + MOD((s.id * 7 + es.id * 3), 38) >= 60 THEN 'B2' ELSE 'C1' END,
       'Published result', (SELECT id FROM app_user WHERE username='teacher1')
FROM student s
JOIN exam_subject es ON es.class_config_id=s.class_config_id;

--rollback DELETE FROM student_mark;
--rollback DELETE FROM exam_subject;
--rollback DELETE FROM exam;

--changeset erp:007-demo-transport-notifications-certificates context:demo
INSERT INTO transport_route (route_code, route_name, vehicle_no, driver_name, driver_phone, attendant_name, capacity) VALUES
 ('R01','Indiranagar – School','KA-01-AB-2045','Ramesh Kumar','+919900000101','Lakshmi Devi',42),
 ('R02','Whitefield – School','KA-01-CD-7781','Suresh Gowda','+919900000102','Mary Joseph',45),
 ('R03','JP Nagar – School','KA-05-EF-1912','Iqbal Ahmed','+919900000103','Shanti Rao',40);

INSERT INTO transport_stop (route_id, stop_name, pickup_time, drop_time, seq_no, monthly_fee)
SELECT r.id, v.stop_name, CAST(v.pickup AS TIME), CAST(v.drop_time AS TIME), v.seq_no, v.fee
FROM transport_route r
JOIN (VALUES
 ('R01','Indiranagar 12th Main','07:15:00','15:45:00',1,2800),
 ('R01','Domlur Flyover','07:28:00','15:32:00',2,2500),
 ('R02','Hope Farm Junction','06:55:00','16:05:00',1,3200),
 ('R02','ITPL Main Gate','07:10:00','15:50:00',2,3000),
 ('R03','JP Nagar 6th Phase','07:05:00','15:55:00',1,2900),
 ('R03','Jayanagar 4th Block','07:25:00','15:35:00',2,2500)
) v(route_code,stop_name,pickup,drop_time,seq_no,fee) ON r.route_code=v.route_code;

INSERT INTO student_transport (student_id, route_id, stop_id)
SELECT s.id, r.id, ts.id
FROM student s
JOIN transport_route r ON r.route_code=CASE WHEN MOD(s.id,3)=0 THEN 'R03' WHEN MOD(s.id,2)=0 THEN 'R02' ELSE 'R01' END
JOIN transport_stop ts ON ts.route_id=r.id AND ts.seq_no=1
WHERE s.id IN (SELECT id FROM student WHERE MOD(id,2)=1);

INSERT INTO user_notification (user_id, title, body, category, read_flag)
SELECT id, 'Welcome to the new parent portal', 'Attendance, fees, timetable, report cards and school notices are now available in one place.', 'GENERAL', FALSE
FROM app_user WHERE username='parent';
INSERT INTO user_notification (user_id, title, body, category, read_flag)
SELECT id, 'Half yearly report card published', 'Aanya''s Half Yearly Examination report card is ready to view.', 'ACADEMIC', FALSE
FROM app_user WHERE username='parent';
INSERT INTO user_notification (user_id, title, body, category, read_flag)
SELECT id, 'Attendance pending', 'Please mark today''s attendance for your assigned classes.', 'ATTENDANCE', FALSE
FROM app_user WHERE username IN ('teacher1','teacher2');
INSERT INTO user_notification (user_id, title, body, category, read_flag)
SELECT id, 'Management snapshot ready', 'Today''s student, attendance and fee collection snapshot is available on the principal dashboard.', 'REPORT', FALSE
FROM app_user WHERE username IN ('principal','admin');

INSERT INTO student_certificate (student_id, certificate_no, certificate_type, title, body_text, issued_on, issued_by_id)
SELECT s.id, 'BON-' || s.admission_no, 'BONAFIDE', 'Bonafide Student Certificate',
       'This is to certify that ' || s.full_name || ' is a bonafide student of our school for the academic year 2027-28.',
       CURRENT_DATE, (SELECT id FROM app_user WHERE username='principal')
FROM student s WHERE s.admission_no IN ('ADM27-00001','ADM27-00021');

--rollback DELETE FROM student_certificate;
--rollback DELETE FROM user_notification;
--rollback DELETE FROM student_transport;
--rollback DELETE FROM transport_stop;
--rollback DELETE FROM transport_route;
